= Meta (part 1)
Eddie
5th July 2020
:source-highlighter: rouge
:nofooter:

link:index.html[[back]]

== Asciidoctor
This page was written in AsciiDoc and generated using
https://asciidoctor.org[Asciidoctor,window=_blank]. I was looking for something
that could produce results similar to what we see in GitHub's pull requests and
gists via their own flavour of Markdown, and the AsciiDoc format seems to
satisfy this.

Having experimented with generating html from md 
https://github.com/edwinek/cv-from-md/[in the past,window=_blank], I had a fair
idea of the features I was looking for:

* ease of use
* self-contained, static output
* support for syntax highlighting

=== Early exploration
Getting set up wasn't as straightforward as I would have hoped; Ubuntu 20.04 is
not configured out-of-the-box for Ruby. Installing Ruby is not hard, however
it wasn't long before I discovered that the suggested `gem` management tool
`bundler`, requires that the default Ruby install requires further configuration
before allowing use by a non-root user. An alternative would be to learn a
little more about Ruby's `rbenv` virtual environments.

=== Live editing
Something in the setup guide that really appealed to me was the idea of being
able to live preview the HTML output of a file as it was being edited. The
suggested approach for this is to use a Ruby gem called `guard` however neither
of the sets of steps in the guide yielded any success for me. I ended up
creating a simple `inotify` script as follows, to re-render the file being
worked on after every save.
[source,shell]
----
#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
	echo "Usage: watch.sh <name of file>" # <1> 
	exit
fi
while true # <2>
do
	inotifywait -qe modify "$1" # <3>
	asciidoctor "$1" # <4>
done
----
<1> I always forget how to use scripts
<2> So that we don't stop after the first save
<3> "Blocks" the script until the first time the specified file is modified
<4> Re-render the html

The `GNOME Web` web browser automatically detects changes in local html files,
and as suggested in the Asciidoctor setup guide is a perfect match for live
editing purposes. I attempted to install this under its old name of 'epiphany'
before discovering that the package of this name is actually a game
(`epiphany-browser` is what I was looking for!).

=== Refinement
Having reached a point where things seemed to be working well enough, I ended up
removing Ruby, the development headers, gems and `.bashrc` changes from my
machine, and created a modified script that used the official Docker image:
[source,shell]
----
#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
	echo "Usage: watch.sh <name of file>"
	exit
fi
docker run --user $(id -u):$(id -g) --rm -it -v "$PWD":/documents/ asciidoctor/docker-asciidoctor sh -c "while true; do inotifywait -qe modify "$1"; asciidoctor "$1"; done"
----

=== Themes
I did some experimentation with theming via the
https://github.com/darshandsoni/asciidoctor-skins[asciidoctor-skins,window=_blank]
project, and it was quick and easy to change the entire theme of a rendered
document, however none of these really took my fancy at this stage. I will say
that I was impressed by how this page looked in Firefox with the
https://github.com/darkreader/darkreader[darkreader,window=_blank] addon.
