= Eddie Campbell
contact <edwin.a.campbell@gmail.com>
:nofooter:

link:index.html[[back]]

I’m a lead engineer at FanDuel, where I work across Scrum teams responsible for
user sign-up and KYC flows. Having transitioned to development from a fairly
extensive test automation career I bring a grounded and quality-focused approach
to what I do.

With a long time personal interest in Linux and networking, I am effective in
modern cloud-based, containerised development environments and have strong
hands-on troubleshooting skills. The streamlining of engineer workflows is
something I am very keen on and so am always on the lookout for pragmatic
opportunities to automate or optimise tasks.

Over the years I have experienced development life-cycles of varying levels of
agility and with this I believe that finding the balance between a pragmatic
approach and best practice is key to success. In addition, enabling others is at
the very core of what is important to me as an engineer and so I aim to include
mentoring and information sharing into what I do.

== Skills
* Programming: Java / Python
* Continuous delivery: Jenkins / AWS / Docker / git
* Linux: Arch / Debian / shell scripting
* RDBMS: Microsoft SQL Server / SQL scripting / Hibernate ORM
* Virtualisation: VMware Workstation / VirtualBox / vSphere

== Experience
=== FanDuel
* *Lead Engineer* - _March 2020 - present_
* *Senior Software Engineer* - _July 2018 - March 2020_
* *Software Engineer* - _June 2017 - July 2018_
- Lead Engineer within the _Account_ vertical.

=== Aquila Insight
* *Automated Test Engineer* - _February 2016 - June 2017_
- Test team lead, responsible for implementing the test framework and processes
  for Aquila’s cloud-based analytics platform.
- I developed UI / API-level tests that are included in the Jenkins / AWS /
  Docker-based continuous delivery environment.
- Tests were written in Cucumber-JVM using Java / Spring 4, and I adopted BDD /
  3A wherever possible, within the dev team’s Scrum workflow.

=== Sky
* *Senior Engineer* - _September 2015 - January 2016_
* *Automation Tester* - _October 2012 - September 2015_
- Part of a small automated test team, using Kanban to track workflow.
  development and maintenance of the test framework that is in place.
- Developed tests for a service-oriented CRM platform using Java, Cucumber-JVM,
  Spring Framework 4 and a host of other other open source libraries.
- Produced UI-based integration tests within a development scrum team, using QTP
  / UFT.

=== Iplay
_Iplay deliver integrated casual games solutions worldwide._

* *Senior Test Engineer / Automation Team Lead* - _April 2012 - October 2012_
- Responsible for driving the implementation and maintenance of automated tests
  across C# (with Nunit / Selenium WebDriver) and Ruby (with Cucumber / Watir
  WebDriver) platforms.

=== QuickTrace Ltd
_QuickTrace provide software for use with clinical systems in healthcare._

* *Software Test Analyst (contract)* - _June 2010 - March 2012_
- Implemented automated test framework and defect tracking procedures.
- Provided extensive test documentation and procedures for its execution.
- Tested integration with solutions from major clinical system suppliers in the
UK and Ireland (including iSOFT, GPASS, EMIS, InPS, TPP).

=== Crocodile Clips Ltd
_Crocodile Clips (now Sumdog) develop engaging educational simulation software
and online arithmetic games._

* *Software Test Manager* - _May 2009 - May 2010_
- Responsible for a team of twelve Test Engineers ensuring smooth running of
  test processes in an Agile SDLC.
- Provided mentoring where test documentation and execution was concerned.  
- Led focus groups of end users in usability testing.

=== Zonal Retail Data Systems
* *Quality Automation Analyst* - _May 2008 - May 2009_
- Responsible for the design and implementation of a QTP / WinRunner-based
  automation framework, running on VMware workstation.
* *Quality Analyst* - _April 2006 - May 2008_
- Authored test cases / test scripts for exercising proprietary hardware and its
  embedded software, as well as desktop software.
- Developed expertise in virtualised environments (VMware) / SQL Server
* *Helpcentre Analyst* - _Nov 2004 - April 2006_
- Remote support for proprietary EPoS hardware

=== Sykes
* *Call Centre Agent* - _July 2004 - Nov 2004_
- Helpdesk for Samsung laptop users

== Qualifications / Awards / Certifications
* Computer Science BEng (hons), University of Edinburgh
* University of Edinburgh Sidney Michaelson Prize winner 2003 / 2004
* ISEB ISTQB Foundation Certificate
* MCDBA - Microsoft Certified Database Administrator (SQL Server 2000)
* MCTS - SQL Server 2005

== Other interests
Outside of tech I enjoy running, weights and playing bass guitar and shouting in
heavy bands.
